version: '3.8'

services:
  db:
    image: mysql:8.2
    restart: always
    ports:
      - "3306:3306"
    environment:   
      MYSQL_DATABASE: ${DB_NAME}       
      MYSQL_USER: ${DB_USERNAME}                    
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    container_name: mysql-db
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql-data: